package messages

import (
	"encoding/hex"
	"strings"
	"testing"
	"unicode/utf8"
)

func TestDecodeAttributedBodyPreservesLeadingNUL(t *testing.T) {
	// NSArchiver.archivedData(withRootObject: NSAttributedString(string: "\u{0}hello"))
	// generated by macOS Foundation, using only synthetic text.
	body, err := hex.DecodeString("040b73747265616d747970656481e803840140848484124e5341747472696275746564537472696e67008484084e534f626a656374008592848484084e53537472696e67019484012b060068656c6c6f86840269490106928484840c4e5344696374696f6e6172790094840169008686")
	if err != nil {
		t.Fatal(err)
	}
	got, ok := decodeAttributedBodyValue(body)
	if !ok || got != "\x00hello" {
		t.Fatalf("decoded text = %q, available=%v", got, ok)
	}
}

func TestDecodeAttributedBodyRejectsMalformedUTF8(t *testing.T) {
	for _, text := range []string{"\xfftail", "prefix\xfftail", "prefix\xff", "prefix\xc3"} {
		if got, ok := decodeAttributedBodyValue(makeStreamtypedAttributedBody(text)); ok || got != "" {
			t.Fatalf("malformed body %q decoded as %q, available=%v", text, got, ok)
		}
	}
}

func FuzzDecodeAttributedBodyRoundTrip(f *testing.F) {
	for _, text := range []string{"", "\x00", "\x00hello", "\x00\x00hello", "café 😀", "\ufeffhello", "hello\x00tail"} {
		f.Add(text)
	}
	for _, length := range []int{127, 128, 255, 256, 65535, 65536} {
		f.Add("\x00" + strings.Repeat("x", length-1))
	}
	f.Fuzz(func(t *testing.T, text string) {
		if !utf8.ValidString(text) {
			t.Skip()
		}
		got, ok := decodeAttributedBodyValue(makeStreamtypedAttributedBody(text))
		if !ok || got != text {
			t.Fatalf("decoded %q as %q, available=%v", text, got, ok)
		}
	})
}
