package messages

import (
	"encoding/hex"
	"strings"
	"testing"
	"unicode/utf8"
)

func TestDecodeAttributedBodyPreservesLeadingNUL(t *testing.T) {
	// NSArchiver.archivedData(withRootObject: NSAttributedString(string: "\u{0}hello"))
	// generated by macOS Foundation, using only synthetic text.
	body, err := hex.DecodeString("040b73747265616d747970656481e803840140848484124e5341747472696275746564537472696e67008484084e534f626a656374008592848484084e53537472696e67019484012b060068656c6c6f86840269490106928484840c4e5344696374696f6e6172790094840169008686")
	if err != nil {
		t.Fatal(err)
	}
	got, ok := decodeAttributedBodyValue(body)
	if !ok || got != "\x00hello" {
		t.Fatalf("decoded text = %q, available=%v", got, ok)
	}
}

func TestDecodeAttributedBodyRejectsMalformedUTF8(t *testing.T) {
	for _, text := range []string{"\xfftail", "prefix\xfftail", "prefix\xff", "prefix\xc3"} {
		if got, ok := decodeAttributedBodyValue(makeStreamtypedAttributedBody(text)); ok || got != "" {
			t.Fatalf("malformed body %q decoded as %q, available=%v", text, got, ok)
		}
	}
}

func TestDecodeAttributedBodyUTF16(t *testing.T) {
	tests := []struct {
		name string
		raw  string
		want string
		ok   bool
	}{
		{"little endian", "\xff\xfe\x00\x00A\x00\x3d\xd8\x00\xde\xfd\xff", "\x00A😀�", true},
		{"big endian", "\xfe\xff\x00\x00\x00A\xd8\x3d\xde\x00\xff\xfd", "\x00A😀�", true},
		{"empty little endian", "\xff\xfe", "", true},
		{"empty big endian", "\xfe\xff", "", true},
		{"odd little endian", "\xff\xfeA\x00B", "", false},
		{"odd big endian", "\xfe\xff\x00A\x00", "", false},
		{"unpaired high little endian", "\xff\xfeA\x00\x3d\xd8", "", false},
		{"unpaired high big endian", "\xfe\xff\x00A\xd8\x3d", "", false},
		{"unpaired low little endian", "\xff\xfeA\x00\x00\xde", "", false},
		{"unpaired low big endian", "\xfe\xff\x00A\xde\x00", "", false},
		{"high then ordinary", "\xff\xfe\x3d\xd8A\x00", "", false},
		{"high then high", "\xfe\xff\xd8\x3d\xd8\x3d", "", false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, ok := decodeAttributedBodyValue(makeStreamtypedAttributedBody(tt.raw))
			if got != tt.want || ok != tt.ok {
				t.Fatalf("decoded %q, available=%v; want %q, available=%v", got, ok, tt.want, tt.ok)
			}
		})
	}
}

func FuzzDecodeAttributedBodyRoundTrip(f *testing.F) {
	for _, text := range []string{"", "\x00", "\x00hello", "\x00\x00hello", "café 😀", "\ufeffhello", "hello\x00tail"} {
		f.Add(text)
	}
	for _, length := range []int{127, 128, 255, 256, 65535, 65536} {
		f.Add("\x00" + strings.Repeat("x", length-1))
	}
	f.Fuzz(func(t *testing.T, text string) {
		if !utf8.ValidString(text) {
			t.Skip()
		}
		got, ok := decodeAttributedBodyValue(makeStreamtypedAttributedBody(text))
		if !ok || got != text {
			t.Fatalf("decoded %q as %q, available=%v", text, got, ok)
		}
	})
}
